[package]
name = "r4s"
version = "0.5.5-PRE"
description = "Manage and serve my blog"
authors = ["Rasmus Kaj <rasmus@krats.se>"]
edition = "2024"

build = "src/build.rs"

[profile.dev]
debug = false

[build-dependencies]
anyhow = "1.0.44"
ructe = { version = "0.18.2", features = ["sass", "warp03"] }

[dependencies]
accept-language = "3.0.1"
anstyle = "1.0.13"
anyhow = "1.0.44"
arborium = { version = "2.3.2", features = [
  "lang-bash",
  "lang-cpp",
  "lang-css",
  "lang-go",
  "lang-html",
  "lang-java",
  "lang-javascript",
  "lang-json",
  "lang-markdown",
  "lang-python",
  "lang-rust",
  "lang-scss",
  "lang-xml"
] }
atom_syndication = "0.12.0"
base64 = "0.22.1"
bytes = "1.10.1"
chrono = { version = "0.4.19", default-features = false }
clap = { version = "4.5.4", features = ["derive", "env", "wrap_help"] }
csrf = "0.5.0"
diesel = { version = "2.3.2", features = ["chrono", "postgres", "network-address"] }
diesel-async = { version = "0.8.0", features = ["deadpool", "postgres"] }
dotenvy = "0.15.7"
fluent = "0.17.0"
gravatar = "0.2.0"
i18n-embed = { version = "0.16.0", features = ["fluent-system"] }
i18n-embed-fl = "0.10.0"
intl-memoizer =  "0.5.1"
ipnetwork = { version = "0.21.1", features = ["serde"] }
lazy-regex = "3.0.0"
mime = "0.3.0"
png = "0.18.0"
pulldown-cmark = "0.13.0"
pulldown-cmark-escape = "0.11.0"
qr_code = "2.0.0"
reqwest = { version = "0.13.1", features = ["blocking", "json", "query"] }
rust-embed = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slug = "0.1"
textwrap = { version = "0.16.0", features = ["terminal_size"] }
thiserror = "2.0.17"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.4", features = ["env-filter"] }
warp = { version = "0.4.2", features = ["server"] }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
doc_markdown = "allow"
if_not_else = "allow"
needless_pass_by_value = "allow"
struct_field_names = "allow"
unnecessary_debug_formatting = "allow"
unnecessary_wraps = "allow"
# This should be allowd specifically in the ructe code.
too_many_lines = "allow"

# Selected "restriction" lints.
cfg_not_test = "warn"
dbg_macro = "warn"
deref_by_slicing = "warn"
# doc_paragraphs_missing_punctuation = "warn" - todo: decide on this
exit = "warn"
large_include_file = "warn"
#panic = "warn"
rc_buffer = "warn"
redundant_test_prefix = "warn"
ref_patterns = "warn"
same_name_method = "warn"
self_named_module_files = "warn"
tests_outside_test_module = "warn"
#todo = "warn"
try_err = "warn"
unimplemented = "warn"
# unneeded_field_pattern = "warn" -- todo
# unreachable = "warn" -- todo
unused_result_ok = "warn"
#unwrap_used = "warn"
# allow_attributes_without_reason = "warn" -- needs work in ructe
